### ISSUE TITLE
Дамп адрес для додавання перевірки їх наявності в openstreetmap

### ISSUE THREAD

**Issue by Andygol** [the-clarity-project/api#1]
https://www.facebook.com/theclarityproject/posts/2252476181451014 

в цьому повідомлені зазначено, що API може парсити та нормалізовувати адреси.

Чи є у вас можливість поширити дамп адрес (без прив'язки до конкретних осіб), що утворився в процесі обробки та аналізу даних з торгів в Проззоро, для перевірки та внесення відсутньої інформації в [openstreetmap](https://osm.org/)?

Зі свого боку ви можете використовувати дані OSM для перевірки назв вулиць та населених пунктів, що були перейменовані в рамках процессу декомунізації.

**Comment by yharahuts** [comment]
Адреси саме з Прозорро не оброблюються (але це теж буде), нормалізація зараз працює лише для даних ЄДРПОУ.

До кінця тижня зроблю дамп.

**Comment by velmyshanovnyi** [comment]
круто!

а можете в дамп вносити також КОАТУУ (для тих обЄктів де це зазначено)

???

**Comment by yharahuts** [comment]
Нажаль, КОАТУУ ніде не зазначено. :(

**Comment by yharahuts** [comment]
CSV-файл, 700к строк, порядка 500 мегабайт распакованный:

http://legl.es/edr_address.zip

**Comment by Andygol** [comment]
@Legless Щиро дякую

**Comment by velmyshanovnyi** [comment]
Опис проблематики для РОЗПАКОВАНОГО http://legl.es/edr_address.zip (станом на 20190401):
1 661 079 (рядків)
949 (МБ) 
995 636 358 (байтів)
стандартними методами відкрити це в екселі НЕ ВИЙДЕ (обмеження в 1М рядків)

Заголовки:

Edr | Name | FullAddress | FormattedAddress | PostalCode | Region | RegionCode | District | Locality | LocalityType | Street | StreetType | Building | BuildingType | Structure | StructureType | Apartment | ApartmentType ;

**Comment by Andygol** [comment]
@velmyshanovnyi так це й не для Екселю. 
RDBMS на власний смак і вперед. Спробуй Access для початку або [Libreoffice Base](https://www.libreoffice.org/discover/base/)

**Comment by velmyshanovnyi** [comment]
я просто побачив вище
"CSV-файл, 700к строк"

думав глянути оком спочатку...
(вже подивився в принципі...)
але варто конвертувати в .sql щось....

**Comment by yharahuts** [comment]
> "CSV-файл, 700к строк"

Там файл час від часу оновлюється, цей - станом на березень, там окрім даних з ЄДР ще є купа іншого.
