### ISSUE TITLE
Вопрос о /edr.info/

### ISSUE THREAD

**Issue by VDSnuff** [the-clarity-project/api#2]
Здравствуйте Legless,

возможно ли включение этих полей "Переможець у 27 054 закупівлях на суму 1 133 142 812.48 грн" ( примерь  https://clarity-project.info/tenderer/32490244) в объект возвращаемый методом  /edr.info/ЕГРПОУ
? 

Спасибо!

**Comment by yharahuts** [comment]
Добрый день.
Добавил на продакшн. 

```
  "tenderer_stats": {
    "awards": {
      "Count": "27060",
      "Value": "1133164936.50"
    }
  }
```
